### ISSUE TITLE
AttributeError: 'BIMPM' object has no attribute 'mp_w1'

### ISSUE THREAD

**Issue by SeekPoint** [galsang/BIMPM-pytorch#3]
mldl@mldlUB1604:~/ub16_prj/BIMPM-pytorch$ python3 train.py
loading SNLI data...
downloading snli_1.0.zip
extracting
.vector_cache/glove.840B.300d.zip: 2.18GB [10:50, 3.35MB/s]                                                                                                                                                 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2196017/2196017 [03:46<00:00, 9702.68it/s]
training start!
epoch: 1
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    main()
  File "train.py", line 137, in main
    best_model = train(args, data)
  File "train.py", line 67, in train
    pred = model(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mldl/ub16_prj/BIMPM-pytorch/model/BIMPM.py", line 265, in forward
    mv_p_full_fw = mp_matching_func(con_p_fw, con_h_fw[:, -1, :], self.mp_w1)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 366, in __getattr__
    type(self).__name__, name))
AttributeError: 'BIMPM' object has no attribute 'mp_w1'

**Comment by galsang** [comment]
Same issue with #2.
